---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-storage
  hostPath:
    path: /mnt/md0/loki-data # gets mapped to whatever is in loki.storage.filesystem.directory
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-export-0-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: grafana-storage
#   hostPath:
#     path: /mnt/lab/k8s_apps/minio-data
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: minio-export-1-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: grafana-storage
#   hostPath:
#     path: /mnt/lab/k8s_apps/minio-data