---
apiVersion: v1
kind: Pod
metadata:
  name: inotify-tuner
  namespace: barnold 
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - at-compute001  # Change this to your target node
  # Target specific worker node
  # nodeSelector:
  #   kubernetes.io/hostname: at-compute001
  
  containers:
  - name: inotify-tuner
    image: busybox:1.33
    command:
    - sh
    - -c
    - |
      echo "=== Current inotify settings ==="
      echo "max_user_instances: $(cat /proc/sys/fs/inotify/max_user_instances)"
      echo "max_user_watches: $(cat /proc/sys/fs/inotify/max_user_watches)"
      echo "max_queued_events: $(cat /proc/sys/fs/inotify/max_queued_events)"
      
      echo "=== Applying new inotify settings ==="
      sysctl -w fs.inotify.max_user_instances=130
      
      echo "=== New inotify settings ==="
      echo "max_user_instances: $(cat /proc/sys/fs/inotify/max_user_instances)"
      echo "max_user_watches: $(cat /proc/sys/fs/inotify/max_user_watches)"
      echo "max_queued_events: $(cat /proc/sys/fs/inotify/max_queued_events)"
      
      echo "=== Current inotify usage ==="
      find /proc/*/fd -lname anon_inode:inotify -exec ls -l {} \; 2>/dev/null | awk '{print $3}' | sort | uniq -c | sort -rn
      
      echo "=== Changes applied successfully! ==="
      echo "Pod will now exit. Changes persist on node until reboot."
    
    securityContext:
      privileged: true
      runAsUser: 0
    
  #   volumeMounts:
  #   - name: proc
  #     mountPath: /proc
  #   - name: sys
  #     mountPath: /sys
  
  # volumes:
  # - name: proc
  #   hostPath:
  #     path: /proc
  # - name: sys
  #   hostPath:
  #     path: /sys
  
  restartPolicy: Never