---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uc-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: uc-storage
  hostPath:
    path: /mnt/md0/uc-data # gets mapped to whatever is in loki.storage.filesystem.directory